### ISSUE TITLE
bail out gracefully if no IP address can be acquired

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic-devmode#3]
I created a VM that had no NIC attached and booted into devmode.

The system was unable to retrieve an IP address and therefore should not attempt to download the Cockpit container.  But this does not happen.

The system proceeds to attempt the download as if nothing was wrong.

![devmode-no-network](https://cloud.githubusercontent.com/assets/10236257/16129852/9824d5a0-33d4-11e6-8e41-290d8fc1eb48.png)

It seems that `get_external_ip` [returns `N\A`](https://github.com/projectatomic/atomic-devmode/blob/master/libexec/init#L122) and the script is checking that the [return does not equal 0](https://github.com/projectatomic/atomic-devmode/blob/master/libexec/init#L69), so it will almost always succeed and proceed.

**Comment by jlebon** [comment]
Ahh right, thanks for the detailed report.
Should be an easy enough fix.
